version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  django-api:
    build:
      context: ./django-api
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_NAME=postgres
      - DJANGO_DATABASE_USER=postgres
      - DJANGO_DATABASE_PASSWORD=postgres
      - OTLP_EXPORTER_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=django-api
      - USE_AZURE_MONITOR=true
      - APPLICATIONINSIGHTS_CONNECTION_STRING=<Your connection string>
    volumes:
      - ./django-api:/app

  flask-api:
    build:
      context: ./flask
    command: flask run --host=0.0.0.0 --port=8001 --reload --extra-files ./templates
    depends_on:
      - django-api
    ports:
      - "8001:8001"
    environment:
      - OTLP_EXPORTER_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=flask-api
      - USE_AZURE_MONITOR=true
      - APPLICATIONINSIGHTS_CONNECTION_STRING=<Your connection string>
    volumes:
      - ./flask/app:/app/app

  fastapi:
    build:
      context: ./fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      - flask-api
    ports:
      - "8002:8002"
    environment:
      - OTLP_EXPORTER_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=fastapi
      - USE_AZURE_MONITOR=true
      - APPLICATIONINSIGHTS_CONNECTION_STRING=<Your connection string>
    volumes:
      - ./fastapi:/app

